services:
  postgres:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=FinalProjectDB'
      - 'MONGO_INITDB_ROOT_PASSWORD=lolcoolporject'
      - 'MONGO_INITDB_ROOT_USERNAME=Cool.Group'
    ports:
      - '27017:27017'