services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=FinalProjectDB'
      - 'POSTGRES_PASSWORD=lolcoolproject'
      - 'POSTGRES_USER=noder_neder'
    ports:
      - '5432:5432'