spring.application.name=Final_Project

server.port=8081

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace


#### SQL CONFIGURATIONS --- 
logging.level.org.springframework.data.mongodb.core.MongoTemplate=trace

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.mongodb.repositories.base-package=server.repositories.mongo
spring.data.redis.repositories.base-package=server.repositories.redis

### use this configuration to create demo entities on server startup
spring.profiles.active=default
#spring.profiles.active=default,AfekaManualGeneration

# =============================
# OpenAI Integration
# =============================
openai.api.key=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

# =============================
# RSS Sources
# =============================
rss.urls=https://www.ynet.co.il/Integration/StoryRss2.xml
