spring.application.name=Final_Project

server.port=8081

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace



#### SQL CONFIGURATIONS --- 
logging.level.org.springframework.data.mongodb.core.MongoTemplate=trace

### use this configuration to create demo entities on server startup
spring.profiles.active=default
#spring.profiles.active=default,AfekaManualGeneration
# =============================
# OpenAI Integration
# =============================
openai.api.key=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
