spring.application.name=2025b.Claudia.Gendler

server.port=8081

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace


#### SQL CONFIGURATIONS --- 
logging.level.org.springframework.data.mongodb.core.MongoTemplate=trace

### use this configuration to create demo entities on server startup
spring.profiles.active=default
#spring.profiles.active=default,AfekaManualGeneration